
mysql:
  container_name: mysql
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: rootpasswd
    MYSQL_DATABASE: drupal
  ports:
    - "3306:3306"


web:
  container_name: thunder
  image: 10.0.3.138:5001/msg-thunder-integration:develop
  environment:
    DRUPAL_TABLE_PREFIX: ~
  ports:
   - "9090:80"

  volumes:
    - ../../harbourmaster-sso-drupal8-plugin:/var/www/html/modules/contrib/hms
    #- ../harbourmaster-sso-drupal8-plugin/js/loginLauncher.js:/var/www/html/modules/contrib/hms/js/loginLauncher.js



   # - ./drupal:/var/www/html
   # - ./config-sync:/var/www/config-sync
   # - ./files:/var/www/html/sites/default/files
   # - ./docker/dev/php.ini:/usr/local/etc/php/php.ini:ro
   # - ./docker/dev/settings.php:/var/www/html/sites/default/settings.php
   # - ./docker/dev/settings.local.php:/var/www/html/sites/default/settings.local.php
   # - ./docker/dev/services.yml:/var/www/html/sites/default/services.yml
  links:
   - mysql