

thunder-usermanager-local:
  container_name: thunder-usermanager-local
  image: valiton/usermanager
  environment:
    NODE_ENV: docker-compose

  env_file:
    - ./second-domain/usermanager_config_second-domain.env
    - ./shared_config.env

  ports:
    - "90:80"

  links:
    - thunder-harbourmaster:harbourmaster
    - redis:redis

  volumes:
    - ./usermanager/vars.less:/app/assets/styles/less/vars.less
    - ./usermanager/white-label.less:/app/assets/styles/less/white-label.less
    - ./usermanager/de.js:/app/assets/languages/de.js
    - ./usermanager/passwordRecoveryHtml.ejs:/app/views/email/forgotPassword/passwordRecoveryHtml.ejs
    - ./usermanager/passwordRecoveryText.ejs:/app/views/email/forgotPassword/passwordRecoveryText.ejs
    - ./usermanager/registrationConfirmationHtml.ejs:/app/views/email/signup/registrationConfirmationHtml.ejs
    - ./usermanager/registrationConfirmationText.ejs:/app/views/email/signup/registrationConfirmationText.ejs


nginx:
  links:
    - thunder-usermanager-local:thunder-usermanager-local
  volumes:
    - ./second-domain/second-domain-nginx.conf:/etc/nginx/conf.d/second-domain-nginx.conf